### ISSUE TITLE
Reset issue

### ISSUE THREAD

**Issue by Martijn735** [s-Pex/VollemansBugs#21] opened 2022-05-24 20:32 UTC
Multiple drivers have problems with crashing the app and that this resets them to the stop

**Comment by Martijn735** [comment] 2022-05-25 13:12
Brad had to reset the app 7 times on 5/25

**Comment by Martijn735** [comment] 2022-05-25 13:14
Nathan had to reset the app 6 Times on 5/24

**Comment by s-Pex** [comment] 2022-06-02 14:30
duplicate of #16

**Closed as not planned by s-Pex** 2022-06-02 14:30 UTC
